name: Test

on:
  workflow_dispatch:

jobs:
  release:
    uses: sevmatic/github-workflows/.github/workflows/release.yml@main
    with:
      plugin: ${{ github.event.repository.name }}
    permissions:
      contents: write
      actions: read
      pull-requests: read
    secrets: inherit
